### ISSUE TITLE
Extend Kepler refactor to include sticker printing and Quantum card generation

### ISSUE THREAD

**Issue by sefrankel** [yarn-co/kepler#12]
A placeholder, add details as necessary, extending and completing work begun in #11

**Comment by sefrankel** [comment]
@tripdragon So we're done here, and you and @semateos are testing / implementing today?

**Comment by tripdragon** [comment]
We have tested and are now at implementing, the new request is to update the load times to a precache. But otherwise this ticket is done.

**Comment by tripdragon** [comment]
kepler is live, the load times have been assigned in triforce as an issue
